#!/usr/bin/env bash
#
# create-jira-feature.sh
# 在 Spec Sub-repo 建立 feature branch 並設定基礎目錄結構
#
# Usage:
#   ./scripts/create-jira-feature.sh <TICKET_ID> "<feature-name>"
#   例如: ./scripts/create-jira-feature.sh PROJ-123 "login-feature"
#

set -euo pipefail

# ─── Colors ───
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ─── Functions ───
log_info()  { echo -e "${BLUE}ℹ️  $*${NC}"; }
log_ok()    { echo -e "${GREEN}✅ $*${NC}"; }
log_warn()  { echo -e "${YELLOW}⚠️  $*${NC}"; }
log_error() { echo -e "${RED}❌ $*${NC}"; }

usage() {
    cat <<EOF
Usage: $(basename "$0") <TICKET_ID> "<feature-name>"

Arguments:
  TICKET_ID      Jira ticket ID (e.g., PROJ-123)
  feature-name   Feature name, will be slugified for branch name

Examples:
  $(basename "$0") PROJ-123 "Login Feature"
  $(basename "$0") PROJ-456 "user-profile"

Environment:
  SPEC_REPO_PATH   Path to the Spec Sub-repo (reads from .env if not set)
  SPEC_REPO_REMOTE Git remote URL for the Spec Sub-repo
EOF
    exit 1
}

slugify() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//'
}

# ─── Load .env ───
load_env() {
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local project_root="${script_dir}/.."
    local env_file="${project_root}/.env"

    if [[ -f "$env_file" ]]; then
        log_info "Loading configuration from .env"
        # shellcheck source=/dev/null
        source "$env_file"
    fi
}

# ─── Validate ───
validate() {
    if [[ -z "${SPEC_REPO_PATH:-}" ]]; then
        log_error "SPEC_REPO_PATH is not set. Run ./install.sh first or set it in .env"
        exit 1
    fi

    if [[ ! -d "$SPEC_REPO_PATH" ]]; then
        log_error "Spec repo not found at: $SPEC_REPO_PATH"
        exit 1
    fi

    if [[ ! -d "$SPEC_REPO_PATH/.git" ]]; then
        log_error "$SPEC_REPO_PATH is not a git repository"
        exit 1
    fi
}

# ─── Main ───
main() {
    if [[ $# -lt 2 ]]; then
        usage
    fi

    local ticket_id="$1"
    local feature_name="$2"
    local slug
    slug=$(slugify "$feature_name")
    local branch_name="${ticket_id}-${slug}"

    load_env
    validate

    log_info "Creating feature branch: ${branch_name}"
    log_info "Spec repo: ${SPEC_REPO_PATH}"

    cd "$SPEC_REPO_PATH"

    # Ensure we're on the latest main/master
    local default_branch
    default_branch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
    log_info "Updating ${default_branch} branch..."
    git checkout "$default_branch" 2>/dev/null || git checkout -b "$default_branch"
    git pull origin "$default_branch" 2>/dev/null || log_warn "Could not pull from remote (might be a new repo)"

    # Check if branch already exists
    if git show-ref --verify --quiet "refs/heads/${branch_name}" 2>/dev/null; then
        log_warn "Branch '${branch_name}' already exists locally. Switching to it."
        git checkout "$branch_name"
    elif git show-ref --verify --quiet "refs/remotes/origin/${branch_name}" 2>/dev/null; then
        log_warn "Branch '${branch_name}' exists on remote. Checking out."
        git checkout -b "$branch_name" "origin/${branch_name}"
    else
        log_info "Creating new branch: ${branch_name}"
        git checkout -b "$branch_name"
    fi

    # Create directory structure for this feature
    local feature_dir="features/${ticket_id}"
    mkdir -p "${feature_dir}/spec"
    mkdir -p "${feature_dir}/plan"

    # Create placeholder files if they don't exist
    if [[ ! -f "${feature_dir}/spec/prd.md" ]]; then
        cat > "${feature_dir}/spec/prd.md" <<PRDEOF
# PRD: ${feature_name}

**Jira Ticket**: ${ticket_id}
**Status**: Draft
**Created**: $(date -Iseconds)

---

> This PRD was auto-generated by specrity.
> Use \`/specrity.pm.specify ${ticket_id}\` to populate this document.
PRDEOF
        log_ok "Created ${feature_dir}/spec/prd.md"
    fi

    if [[ ! -f "${feature_dir}/plan/plan.md" ]]; then
        cat > "${feature_dir}/plan/plan.md" <<PLANEOF
# Implementation Plan: ${feature_name}

**Jira Ticket**: ${ticket_id}
**Status**: Not Started
**Created**: $(date -Iseconds)

---

> This plan was auto-generated by specrity.
> Use \`/specrity.dev.plan ${ticket_id}\` to populate this document.
PLANEOF
        log_ok "Created ${feature_dir}/plan/plan.md"
    fi

    # Stage and commit
    git add "${feature_dir}/"
    if git diff --cached --quiet; then
        log_info "No new files to commit (directory already exists)"
    else
        git commit -m "feat(${ticket_id}): initialize feature structure for ${feature_name}"
        log_ok "Committed initial feature structure"
    fi

    # Push to remote
    log_info "Pushing branch to remote..."
    if git push -u origin "$branch_name" 2>/dev/null; then
        log_ok "Branch pushed successfully"
    else
        log_warn "Could not push to remote. You may need to push manually:"
        echo "  git push -u origin ${branch_name}"
    fi

    echo ""
    log_ok "Feature branch setup complete!"
    echo ""
    echo "  Branch:    ${branch_name}"
    echo "  Spec dir:  ${feature_dir}/spec/"
    echo "  Plan dir:  ${feature_dir}/plan/"
    echo ""
    echo "  Next step: Run /specrity.pm.specify ${ticket_id} to start the PRD process"
}

main "$@"
